### ISSUE TITLE
Mainnet: OPUL/ALGO Pool Returning Wrong Quote

### ISSUE THREAD

**Issue by albertshin** [tinymanorg/tinyman-py-sdk#13]
Running the following on mainnet:

```
ALGO = client.fetch_asset(0)
OPUL = client.fetch_asset(287867876)
pool3 = client.fetch_pool(OPUL, ALGO)
quote = pool.fetch_fixed_input_swap_quote(ALGO(2500), slippage=0.01)
```

returns, for example, 2955 as `quote`.

In reality, this is actually 0.2955, so the quote is actually is off by exactly **10000** for some reason.

**Comment by fergalwalsh** [comment]
I think the issue here is due to the differing number of decimals per asset.

All amounts and prices in the SDK are expressed in terms of the microunits of the assets. The prices/amounts you see displayed in the Tinyman UI are adjusted according to the defined number of decimals for the asset. All internal calculation on the blockchain and in the SDKs use the microunit integer representation.

When you write `ALGO(2500)` it means 0.002500 Algo because Algo has 6 decimals.
2500.0 Algo would be `ALGO(2500_000_000)`.

Opul has 10 decimals so 1000 in microunits for example is actually 0.0000001 Opul.

While the display price or ratio between the assets might be 1:0.2955 the actual ratio of their microunits could be 1:2955 due to the difference in the number of decimals.

**Comment by albertshin** [comment]
Hi, this seems to be an issue in v1.1. I understand @fergalwalsh's comment on differing decimals and "adjust" for this after I get the quote from the pool, but it seems that `fetch_fixed_input_swap_quote` is assuming that the number of decimals is the same across all units which does not seem to be the expected output for some pools where the input and output have different decimals.

**Comment by cobang** [comment]
@albertshin, Can you please share an example? It would be great to share an example code with expected and real values.

**Comment by cobang** [comment]
Microunits don't have an decimal place. Microunit should be an integer, so your expectation`0.2955` is not valid.

> fetch_fixed_input_swap_quote is assuming that the number of decimals
I think, you don't need to consider decimal place in this calculation, since microunits don't have an decimal place.

**Comment by albertshin** [comment]
I see what you mean. Re-reading Fergal's original reply that everything is expressed in microunits makes more sense. Thanks!
